### ISSUE TITLE
Newline character issue (not works on linux)

### ISSUE THREAD

**Issue by pmh-only** [Deplux/dpt#1]
### Problem
Uploaded npm binary has `CRLF` instead of `LF`.

### Solution
Please replace `CRLF (\r\n)` with `LF (\n)`.

### Enviroment
* linux 5.9.14-arch1-1
* node 15

### Screenshots
![image](https://user-images.githubusercontent.com/39158228/103387769-eb291a00-4b48-11eb-98db-75b20bf8facd.png)
![image](https://user-images.githubusercontent.com/39158228/103387840-54109200-4b49-11eb-8e8b-6508473ca854.png)

EDIT: add enviroment infomation

**Comment by pmh-only** [comment]
@AkiaCode  that's not a bug, just latest package uploader uses windows (maybe)

EDIT: grammar

**Comment by comjun04** [comment]
Can Reproduce
Android 8, Termux, Node 15
![Capture+_2020-12-31-09-48-14.png](https://user-images.githubusercontent.com/30339539/103388620-5d9bf900-4b4d-11eb-939d-334a8ba9babb.png)

**Comment by AkiaCode** [comment]
> @AkiaCode that's not bug, just latest package uploader uses windows (maybe)

I look like a bug

**Comment by pmh-only** [comment]
> > @AkiaCode that's not bug, just latest package uploader uses windows (maybe)
> 
> I look like a bug

umm okay

**Comment by ericlee05** [comment]
It looks like binary script problem.
I wrote this binary script like this :
```
#!/usr/bin/env node
require("./dist/App.js");
```

I'll try to change from CRLF to LF in this file.

**Comment by pmh-only** [comment]
~~package has been updated, but it ended without any progress~~

EDIT: sorry, after type `yarn init`, it works
![image](https://user-images.githubusercontent.com/39158228/103390382-81643c80-4b57-11eb-96ce-60017409550e.png)

**Comment by pmh-only** [comment]
now it works! thx @VINTO1819
