### ISSUE TITLE
Node.js 프로젝트 생성시 node_modules 폴더 제외

### ISSUE THREAD

**Issue by comjun04** [Deplux/dpt#2]
node.js 프로젝트로 zip 파일을 제작하려고 시도하면, `node_modules` 폴더도 포함시켜서 압축합니다.

서버에 배포 시 모듈을 자동 설치하는 작업이 있기 때문에, 이 폴더를 제외하고 압축을 진행해야 할 것 같습니다.

**Comment by ericlee05** [comment]
archiver.js에 있는 glob의 ignore 옵션을 통해서 해결해보도록 하겠습니다 감사합니다.

**Comment by steven1103** [comment]
넵 고치면 @VINTO1819 님이 이슈 닫아주세요

**Comment by pmh-only** [comment]
go언어로 마이그레이션 작업중 적용되었습니다\
#3 에서 처리 관련 이슈를 진행중입니다
